# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Server CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./Server

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create env file
      id: dotenv
      uses: ./.github/actions/dotenv-action
      run: |
        touch .env
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

    - name: Buidling using Node.js ${{ matrix.node-version }}.
      env:
        CI: true
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: Server/package-lock.json
    - run: npm ci
    - run: npm run build --if-present

    - name: Running Jest tests
      run: npm test

    - name: Uploading coverage to Codecov
      uses: codecov/codecov-action@v2
